---
title: "Assignment 1"
author: "72304725"
date: "September 29 2023"
output: html_document
---

```{r setup, include=FALSE} 
# this chunk contains code that sets global options for the entire .Rmd. 
# we use include=FALSE to suppress it from the top of the document, but it will still appear in the appendix. 

knitr::opts_chunk$set(echo = FALSE) # actually set the global chunk options. 
# we set echo=FALSE to suppress code such that it by default does not appear throughout the document. 
# note: this is different from .Rmd default
```

### Exercise 1

Here, I will present the results of writing a for loop to print out the numbers from 1 to 20.

```{r ex1}

# For loop to print numbers
for (i in 1:20) {
  print(i)
}

```

This prints the numbers 1 to 20, each on a separate line.

### Exercise 2

Here, I will print 10 random numbers from the uniform distribution. 

```{r ex2}

# Draw 10 draws from a uniform distribution
runif(10)

```

This drew 10 random numbers from the uniform distribution. This completes the second exercise. 

## Appendix: All code in this assignment

```{r ref.label=knitr::all_labels(), echo=TRUE, eval=FALSE} 
# this chunk generates the complete code appendix. 
# eval=FALSE tells R not to run (``evaluate'') the code here (it was already run before).
```
